var annotated =
[
    [ "face", null, [
      [ "Body", "classface_1_1_body.html", "classface_1_1_body" ],
      [ "Configuration", "classface_1_1_configuration.html", "classface_1_1_configuration" ],
      [ "ExceptionDescriptor", "classface_1_1_exception_descriptor.html", "classface_1_1_exception_descriptor" ],
      [ "FileSystem", "classface_1_1_file_system.html", "classface_1_1_file_system" ],
      [ "GarbageCollector", "classface_1_1_garbage_collector.html", "classface_1_1_garbage_collector" ],
      [ "GlobalSettings", "classface_1_1_global_settings.html", "classface_1_1_global_settings" ],
      [ "Message", "classface_1_1_message.html", "classface_1_1_message" ],
      [ "MetaData", "classface_1_1_meta_data.html", "classface_1_1_meta_data" ],
      [ "Node", "classface_1_1_node.html", "classface_1_1_node" ],
      [ "PortNameParser", "classface_1_1_port_name_parser.html", "classface_1_1_port_name_parser" ],
      [ "StopwatchTimer", "classface_1_1_stopwatch_timer.html", "classface_1_1_stopwatch_timer" ],
      [ "StringBuilder", "classface_1_1_string_builder.html", "classface_1_1_string_builder" ],
      [ "Timer", "classface_1_1_timer.html", "classface_1_1_timer" ],
      [ "TimeStamp", "classface_1_1_time_stamp.html", "classface_1_1_time_stamp" ],
      [ "Tracer", "classface_1_1_tracer.html", "classface_1_1_tracer" ],
      [ "XmlReader", "classface_1_1_xml_reader.html", "classface_1_1_xml_reader" ],
      [ "AlgorithmList", "classface_1_1_algorithm_list.html", "classface_1_1_algorithm_list" ],
      [ "FaceController", "classface_1_1_face_controller.html", "classface_1_1_face_controller" ],
      [ "ModuleGraph", "classface_1_1_module_graph.html", "classface_1_1_module_graph" ],
      [ "AAMBody", "classface_1_1_a_a_m_body.html", "classface_1_1_a_a_m_body" ],
      [ "AAMNode", "classface_1_1_a_a_m_node.html", "classface_1_1_a_a_m_node" ],
      [ "AAMParam", "classface_1_1_a_a_m_param.html", "classface_1_1_a_a_m_param" ],
      [ "Algorithm", "classface_1_1_algorithm.html", "classface_1_1_algorithm" ],
      [ "AlgorithmFactory", "classface_1_1_algorithm_factory.html", "classface_1_1_algorithm_factory" ],
      [ "EmptyBody", "classface_1_1_empty_body.html", "classface_1_1_empty_body" ],
      [ "EmptyMessage", "classface_1_1_empty_message.html", "classface_1_1_empty_message" ],
      [ "EmptyNode", "classface_1_1_empty_node.html", "classface_1_1_empty_node" ],
      [ "HaarDetectorBody", "classface_1_1_haar_detector_body.html", "classface_1_1_haar_detector_body" ],
      [ "HaarDetectorNode", "classface_1_1_haar_detector_node.html", "classface_1_1_haar_detector_node" ],
      [ "HaarDetectorParam", "classface_1_1_haar_detector_param.html", "classface_1_1_haar_detector_param" ],
      [ "ImageMessage", "classface_1_1_image_message.html", "classface_1_1_image_message" ],
      [ "LimitDecrementerBody", "classface_1_1_limit_decrementer_body.html", "classface_1_1_limit_decrementer_body" ],
      [ "ModuleFactory", "classface_1_1_module_factory.html", "classface_1_1_module_factory" ],
      [ "RectangleMessage", "classface_1_1_rectangle_message.html", "classface_1_1_rectangle_message" ],
      [ "SourceBody", "classface_1_1_source_body.html", "classface_1_1_source_body" ],
      [ "SourceLimiterNode", "classface_1_1_source_limiter_node.html", "classface_1_1_source_limiter_node" ],
      [ "SourceNode", "classface_1_1_source_node.html", "classface_1_1_source_node" ],
      [ "SourceParam", "classface_1_1_source_param.html", "classface_1_1_source_param" ],
      [ "TestAlgorithm", "classface_1_1_test_algorithm.html", "classface_1_1_test_algorithm" ]
    ] ]
];